# Generated by Django 3.1.7 on 2021-04-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblprojectintroduction',
            options={'managed': True},
        ),
    ]
