# Generated by Django 3.1.7 on 2021-04-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblClub',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=6)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_path', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'tbl_club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblClubTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_club_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProjectIntroduction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_project_introduction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProjectIntroductionImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_project_introduction_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_tag',
                'managed': False,
            },
        ),
    ]
