# Generated by Django 3.1.7 on 2021-04-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_project', '0002_tblclub_tblclubtag_tblprojectintroduction_tblprojectintroductionimage_tbltag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblprojectintroduction',
            options={'managed': True},
        ),
    ]
