# Generated by Django 3.1.7 on 2021-04-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_project', '0003_auto_20210405_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblprojectintroduction',
            options={},
        ),
        migrations.AddField(
            model_name='tblprojectintroduction',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblprojectintroduction',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblprojectintroduction',
            name='tbl_club',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='club_project.tblclub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblprojectintroduction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tblprojectintroduction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
